// Copyright (c) DEMA Consulting
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System.Reflection;
using System.Resources;

namespace DemaConsulting.SysML2Tools;

/// <summary>
///     Hand-written, culture-aware accessor for the strings embedded in
///     <c>ProgramStrings.resx</c>. Deliberately not generated by the Visual Studio
///     "ResXFileCodeGenerator" custom tool, because that generator only runs inside Visual
///     Studio and is not invoked by <c>dotnet build</c>/CI — this class must build identically
///     everywhere <c>dotnet build</c> runs (net10.0, any OS, any IDE or none).
/// </summary>
/// <remarks>
///     Adding a future locale requires zero code changes: place a
///     <c>ProgramStrings.{culture}.resx</c> file (e.g. <c>ProgramStrings.fr.resx</c>) alongside
///     this file with the same key names, and the .NET SDK's default resx-embedding behavior
///     produces a satellite assembly that <see cref="ResourceManager"/> discovers automatically
///     based on the current UI culture, falling back to this invariant (English) resource set
///     when no matching satellite assembly is found.
/// </remarks>
internal static class ProgramStrings
{
    private static readonly ResourceManager ResourceManager =
        new("DemaConsulting.SysML2Tools.ProgramStrings", typeof(ProgramStrings).Assembly);

    /// <summary>Gets the "SysML2 Tools version {0}" banner format string.</summary>
    public static string Banner_Version => ResourceManager.GetString(nameof(Banner_Version))!;

    /// <summary>Gets the banner copyright line.</summary>
    public static string Banner_Copyright => ResourceManager.GetString(nameof(Banner_Copyright))!;

    /// <summary>Gets the top-level usage line.</summary>
    public static string TopLevel_Usage => ResourceManager.GetString(nameof(TopLevel_Usage))!;

    /// <summary>Gets the "Commands:" header line.</summary>
    public static string TopLevel_CommandsHeader => ResourceManager.GetString(nameof(TopLevel_CommandsHeader))!;

    /// <summary>Gets the 'lint' command summary line.</summary>
    public static string TopLevel_CommandLint => ResourceManager.GetString(nameof(TopLevel_CommandLint))!;

    /// <summary>Gets the 'render' command summary line.</summary>
    public static string TopLevel_CommandRender => ResourceManager.GetString(nameof(TopLevel_CommandRender))!;

    /// <summary>Gets the first line of the 'query' command summary.</summary>
    public static string TopLevel_CommandQuery1 => ResourceManager.GetString(nameof(TopLevel_CommandQuery1))!;

    /// <summary>Gets the second line of the 'query' command summary.</summary>
    public static string TopLevel_CommandQuery2 => ResourceManager.GetString(nameof(TopLevel_CommandQuery2))!;

    /// <summary>Gets the third line of the 'query' command summary.</summary>
    public static string TopLevel_CommandQuery3 => ResourceManager.GetString(nameof(TopLevel_CommandQuery3))!;

    /// <summary>Gets the first line of the 'export' command summary.</summary>
    public static string TopLevel_CommandExport1 => ResourceManager.GetString(nameof(TopLevel_CommandExport1))!;

    /// <summary>Gets the second line of the 'export' command summary.</summary>
    public static string TopLevel_CommandExport2 => ResourceManager.GetString(nameof(TopLevel_CommandExport2))!;

    /// <summary>Gets the first line of the 'help' command summary.</summary>
    public static string TopLevel_CommandHelp1 => ResourceManager.GetString(nameof(TopLevel_CommandHelp1))!;

    /// <summary>Gets the second line of the 'help' command summary.</summary>
    public static string TopLevel_CommandHelp2 => ResourceManager.GetString(nameof(TopLevel_CommandHelp2))!;

    /// <summary>Gets the "Options:" header line.</summary>
    public static string TopLevel_OptionsHeader => ResourceManager.GetString(nameof(TopLevel_OptionsHeader))!;

    /// <summary>Gets the --version option line.</summary>
    public static string TopLevel_OptionVersion => ResourceManager.GetString(nameof(TopLevel_OptionVersion))!;

    /// <summary>Gets the --help option line.</summary>
    public static string TopLevel_OptionHelp => ResourceManager.GetString(nameof(TopLevel_OptionHelp))!;

    /// <summary>Gets the --silent option line.</summary>
    public static string TopLevel_OptionSilent => ResourceManager.GetString(nameof(TopLevel_OptionSilent))!;

    /// <summary>Gets the --validate option line.</summary>
    public static string TopLevel_OptionValidate => ResourceManager.GetString(nameof(TopLevel_OptionValidate))!;

    /// <summary>Gets the --results option line.</summary>
    public static string TopLevel_OptionResults => ResourceManager.GetString(nameof(TopLevel_OptionResults))!;

    /// <summary>Gets the first line of the --depth option description.</summary>
    public static string TopLevel_OptionDepth1 => ResourceManager.GetString(nameof(TopLevel_OptionDepth1))!;

    /// <summary>Gets the second line of the --depth option description.</summary>
    public static string TopLevel_OptionDepth2 => ResourceManager.GetString(nameof(TopLevel_OptionDepth2))!;

    /// <summary>Gets the third line of the --depth option description.</summary>
    public static string TopLevel_OptionDepth3 => ResourceManager.GetString(nameof(TopLevel_OptionDepth3))!;

    /// <summary>Gets the --log option line.</summary>
    public static string TopLevel_OptionLog => ResourceManager.GetString(nameof(TopLevel_OptionLog))!;

    /// <summary>Gets the --output option line.</summary>
    public static string TopLevel_OptionOutput => ResourceManager.GetString(nameof(TopLevel_OptionOutput))!;

    /// <summary>Gets the first line of the --format option description.</summary>
    public static string TopLevel_OptionFormat1 => ResourceManager.GetString(nameof(TopLevel_OptionFormat1))!;

    /// <summary>Gets the second line of the --format option description.</summary>
    public static string TopLevel_OptionFormat2 => ResourceManager.GetString(nameof(TopLevel_OptionFormat2))!;

    /// <summary>Gets the third line of the --format option description.</summary>
    public static string TopLevel_OptionFormat3 => ResourceManager.GetString(nameof(TopLevel_OptionFormat3))!;

    /// <summary>Gets the --view option line.</summary>
    public static string TopLevel_OptionView => ResourceManager.GetString(nameof(TopLevel_OptionView))!;

    /// <summary>Gets the --auto option line.</summary>
    public static string TopLevel_OptionAuto => ResourceManager.GetString(nameof(TopLevel_OptionAuto))!;

    /// <summary>Gets the first line (flag names) of the --element option description.</summary>
    public static string TopLevel_OptionElement1 => ResourceManager.GetString(nameof(TopLevel_OptionElement1))!;

    /// <summary>Gets the second line (description) of the --element option description.</summary>
    public static string TopLevel_OptionElement2 => ResourceManager.GetString(nameof(TopLevel_OptionElement2))!;

    /// <summary>Gets the --direction option line.</summary>
    public static string TopLevel_OptionDirection => ResourceManager.GetString(nameof(TopLevel_OptionDirection))!;

    /// <summary>Gets the --kind option line.</summary>
    public static string TopLevel_OptionKind => ResourceManager.GetString(nameof(TopLevel_OptionKind))!;

    /// <summary>Gets the --name option line.</summary>
    public static string TopLevel_OptionName => ResourceManager.GetString(nameof(TopLevel_OptionName))!;

    /// <summary>Gets the --include-stdlib option line.</summary>
    public static string TopLevel_OptionIncludeStdlib => ResourceManager.GetString(nameof(TopLevel_OptionIncludeStdlib))!;

    /// <summary>Gets the "No command specified" message.</summary>
    public static string NoCommand_Message => ResourceManager.GetString(nameof(NoCommand_Message))!;
}
